import type { Metadata } from "next";
import { Inter,Kumbh_Sans, Roboto } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

const kumbhSans = Kumbh_Sans({
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal'],
  subsets: ['latin'],
});
const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: "Bodmate meeting app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kumbhSans.className} ${roboto.className} bg-dark-2 `}>{children}</body>
    </html>
  );
}
